minimumReleaseAge: 720
minimumReleaseAgeExclude:
  - typebox
  - tsuit
packages:
  - "packages/amperjs"
  - "packages/core/*"
  - "packages/generators/*"
  - "packages/formatters/*"
  - "packages/build/*"
